import type { User, Business, Driver } from '../types';

// Mock data for users
export const mockUsers: User[] = [
    {
        id: '1',
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '+963 999 999 999',
        governorate: 'Damascus',
        status: 'active',
        verified: true,
        walletBalance: 5000,
        points: 120,
        joinedDate: '2024-01-15',
    },
    {
        id: '2',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '+963 988 888 888',
        governorate: 'Aleppo',
        status: 'active',
        verified: true,
        walletBalance: 3200,
        points: 85,
        joinedDate: '2024-02-20',
    },
    {
        id: '3',
        name: 'Ahmed Hassan',
        email: 'ahmed.hassan@example.com',
        phone: '+963 977 777 777',
        governorate: 'Homs',
        status: 'inactive',
        verified: false,
        walletBalance: 1500,
        points: 45,
        joinedDate: '2024-03-10',
    },
    {
        id: '4',
        name: 'Sara Ali',
        email: 'sara.ali@example.com',
        phone: '+963 966 666 666',
        governorate: 'Damascus',
        status: 'active',
        verified: true,
        walletBalance: 7800,
        points: 200,
        joinedDate: '2024-01-05',
    },
    {
        id: '5',
        name: 'Mohammed Khalil',
        email: 'mohammed.khalil@example.com',
        phone: '+963 955 555 555',
        governorate: 'Latakia',
        status: 'active',
        verified: true,
        walletBalance: 4200,
        points: 95,
        joinedDate: '2024-02-15',
    },
];

// Mock data for businesses
export const mockBusinesses: Business[] = [
    {
        id: '1',
        name: 'The Grand Restaurant',
        ownerEmail: 'owner@grandrestaurant.com',
        type: 'Restaurant',
        appType: 'Pass',
        city: 'Damascus',
        rating: 4.5,
        status: 'active',
        createdDate: '2024-01-10',
    },
    {
        id: '2',
        name: 'City Cafe',
        ownerEmail: 'info@citycafe.com',
        type: 'Cafe',
        appType: 'Pass',
        city: 'Aleppo',
        rating: 4.2,
        status: 'active',
        createdDate: '2024-02-15',
    },
    {
        id: '3',
        name: 'Health Plus Clinic',
        ownerEmail: 'contact@healthplus.com',
        type: 'Healthcare',
        appType: 'Care',
        city: 'Damascus',
        rating: 4.8,
        status: 'active',
        createdDate: '2024-01-20',
    },
    {
        id: '4',
        name: 'Beauty Salon Elite',
        ownerEmail: 'info@beautyelite.com',
        type: 'Beauty',
        appType: 'Care',
        city: 'Homs',
        rating: 4.6,
        status: 'pending',
        createdDate: '2024-03-01',
    },
    {
        id: '5',
        name: 'Fresh Grocery Store',
        ownerEmail: 'contact@freshgrocery.com',
        type: 'Grocery',
        appType: 'Go',
        city: 'Latakia',
        rating: 4.3,
        status: 'active',
        createdDate: '2024-02-10',
    },
    {
        id: '6',
        name: 'Quick Mart',
        ownerEmail: 'info@quickmart.com',
        type: 'Grocery',
        appType: 'Go',
        city: 'Damascus',
        rating: 4.0,
        status: 'inactive',
        createdDate: '2024-01-25',
    },
];

// Mock data for drivers
export const mockDrivers: Driver[] = [
    {
        id: '1',
        name: 'Ali Mohammed',
        email: 'ali.driver@example.com',
        phone: '+963 944 444 444',
        vehicleType: 'Motorcycle',
        status: 'active',
        availability: 'available',
        rating: 4.8,
        totalDeliveries: 1234,
        earnings: 15000,
    },
    {
        id: '2',
        name: 'Khaled Ahmad',
        email: 'khaled.driver@example.com',
        phone: '+963 933 333 333',
        vehicleType: 'Car',
        status: 'active',
        availability: 'busy',
        rating: 4.6,
        totalDeliveries: 987,
        earnings: 12500,
    },
    {
        id: '3',
        name: 'Omar Hassan',
        email: 'omar.driver@example.com',
        phone: '+963 922 222 222',
        vehicleType: 'Van',
        status: 'active',
        availability: 'available',
        rating: 4.9,
        totalDeliveries: 1567,
        earnings: 18000,
    },
    {
        id: '4',
        name: 'Youssef Ali',
        email: 'youssef.driver@example.com',
        phone: '+963 911 111 111',
        vehicleType: 'Motorcycle',
        status: 'inactive',
        availability: 'offline',
        rating: 4.3,
        totalDeliveries: 456,
        earnings: 5000,
    },
];
